apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-com-tls
spec:
  secretName: myapp-ingress-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: {{ .Values.casIssuer.issuerName }}
    kind: GoogleCASClusterIssuer
    group: cas-issuer.jetstack.io
  commonName: {{ .Values.ingress.hostname }}
  dnsNames:
    - {{ .Values.ingress.hostname }}
  usages:
    - digital signature
    - key encipherment
    - server auth

