apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
spec:
  secretName: {{ .Values.certificate.secretName }}
  duration: {{ .Values.certificate.duration }}
  renewBefore: {{ .Values.certificate.renewBefore }}
  issuerRef:
    name: {{ .Values.certificate.issuerRef.name | default .Values.googleCAS.clusterIssuer.name }}
    kind: {{ .Values.certificate.issuerRef.kind | default "GoogleCASClusterIssuer" }}
    group: {{ .Values.certificate.issuerRef.group | default "cas-issuer.jetstack.io" }}
  commonName: {{ .Values.certificate.commonName }}
  dnsNames:
    {{- toYaml .Values.certificate.dnsNames | nindent 4 }}
  usages:
    - digital signature
    - key encipherment
    - server auth