apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbac.clusterRole.name }}
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
rules:
  # CAS Issuer permissions
  - apiGroups: [ "cas-issuer.jetstack.io" ]
    resources:
      - "googlecasissuers"
      - "googlecasissuers/status"
      - "googlecasclusterissuers"
      - "googlecasclusterissuers/status"
    verbs:
      - get
      - list
      - watch
      - update
      - patch
      - create

  # Cert-manager core permissions
  - apiGroups: [ "cert-manager.io" ]
    resources:
      - "certificaterequests"
      - "certificaterequests/status"
      - "certificaterequests/finalizers"
      - "certificates"
      - "certificates/status"
    verbs:
      - get
      - list
      - watch
      - update
      - patch
      - create
      - delete

  # Signer approval permissions
  - apiGroups: [ "cert-manager.io" ]
    resources:
      - "signers"
    resourceNames:
      - "googlecasissuers.cas-issuer.jetstack.io/*"
      - "googlecasclusterissuers.cas-issuer.jetstack.io/*"
    verbs:
      - approve
      - update

  # Secrets management
  - apiGroups: [ "" ]
    resources:
      - "secrets"
    verbs:
      - get
      - create
      - update
      - patch
      - list
      - delete

  # Certificate signing requests
  - apiGroups: [ "certificates.k8s.io" ]
    resources:
      - "certificatesigningrequests"
      - "certificatesigningrequests/approval"
      - "certificatesigningrequests/status"
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch

  # Events
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "create", "patch", "update" ]

  # Leader election leases
  - apiGroups: [ "coordination.k8s.io" ]
    resources: [ "leases" ]
    verbs: [ "get", "create", "update", "patch" ]

  # Additional monitoring permissions
  - apiGroups: [ "" ]
    resources: [ "pods", "services", "endpoints" ]
    verbs: [ "get", "list", "watch" ]