cert-manager:
  enabled: false # set to true only if you want to install it via this chart
  installCRDs: true
  serviceAccount:
    annotations:
      iam.gke.io/gcp-service-account: "cert-manager-cas-issuer-sa@${project_id}.iam.gserviceaccount.com"

istio:
  gateways:
    istio-ingressgateway:
      service:
        type: LoadBalancer

casIssuer:
  projectId: ""
  location: "europe-west1"
  caPool: ""
  issuerName: "cas-issuer"

ingress:
  hostname: "example.com"
  namespace: "istio-system"
  secretName: "myapp-ingress-tls"