apiVersion: cas-issuer.jetstack.io/v1beta1
kind: GoogleCASIssuer
metadata:
  name: my-googlecas-issuer
  namespace: cert-manager
spec:
  project: "db-demo-int"
  location: "europe-west1"
  caPoolId: "db-ca-pool5"
#    signer: "projects/db-demo-int/locations/us-central1/caPools/db-ca-pool5"
  workloadIdentity:
    serviceAccountRef:
      name: "cert-manager-cas-issuer-sa"
      namespace: "cert-manager"

---

apiVersion: cas-issuer.jetstack.io/v1beta1
kind: GoogleCASClusterIssuer
metadata:
  name: my-googlecas-clusterissuer
spec:
  project: "db-demo-int"
  location: "europe-west1"
  caPoolId: "db-ca-pool5"
  workloadIdentity:
    serviceAccountRef:
      name: "cert-manager-cas-issuer-sa"
      namespace: "cert-manager"