apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: google-cas-issuer
spec:
  googleCAS:
    project: "db-demo-int"
    location: "europe-west1"
    caPool: "db-ca-pool4"
    signer: "projects/db-demo-int/locations/europe-west1/caPools/db-ca-pool4"
    workloadIdentity:
      serviceAccountRef:
        name: "cert-manager-cas-issuer-sa"
        namespace: "cert-manager"
