apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.casIssuer.issuerName }}
spec:
  ca:
    secretName: cas-issuer-root-ca
  googlecas:
    project: {{ .Values.casIssuer.projectId }}
    location: {{ .Values.casIssuer.location }}
    caPool: {{ .Values.casIssuer.caPool }}