apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ingress.hostname }}-tls
spec:
  secretName: {{ .Values.ingress.secretName }}
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: {{ .Values.casIssuer.issuerName }}
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: {{ .Values.ingress.hostname }}
  dnsNames:
    - {{ .Values.ingress.hostname }}
  usages:
    - server auth
    - client auth