apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-cas-issuer-approver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-google-cas-issuer
subjects:
  - kind: ServiceAccount
    name: cert-manager-cas-issuer-sa
    namespace: cert-manager