apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.myapp.serviceName }}
  namespace: {{ .Values.myapp.namespace }}
spec:
  selector:
    app: {{ .Values.myapp.name }}
  ports:
    - port: 80
      targetPort: {{ .Values.myapp.containerPort }}
      protocol: TCP
