apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.ingress.hostname }}-vs
  namespace: {{ .Values.ingress.namespace  | replace "." "-" }}
spec:
  hosts:
    - {{ .Values.ingress.hostname }}
  gateways:
    - {{ .Values.ingress.namespace }}/{{ .Values.ingress.hostname  | replace "." "-" }}-gateway
  http:
      - route:
        - destination:
            host: myapp-service.default.svc.cluster.local
            port:
              number: 80