apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-cas-issuer-sa
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "cert-manager-google-cas-issuer.labels" . | indent 4 }}
  annotations:
{{- toYaml .Values.serviceAccount.annotations | nindent 4 }}

